### ISSUE TITLE
3.2 Implement CSS styling

### ISSUE THREAD

**Issue by Ayas039** [Mohith-Kumar-07/Student_schedule_App#13]
Description:
This task focuses on improving the user interface (UI) and user experience (UX) of the Detailed Course View through the application of CSS styling. The goal is to create a visually appealing and responsive layout that ensures usability across multiple devices, including desktop, tablet, and mobile screens. Special attention should be given to providing a clean, structured design that highlights key course information while maintaining a consistent aesthetic across the platform.

Acceptance Criteria:

The Detailed Course View should render correctly on devices of different sizes, from small mobile screens to larger desktop monitors.

Styling should maintain consistency with the application’s overall design language, ensuring it doesn’t look out of place.

The interface should be intuitive and clean, with no unnecessary clutter, enabling users to quickly access course information.

Visual testing should show no broken elements or overlaps in different screen resolutions and browser types.

**Comment by Mohith-Kumar-07** [comment]
Completed it with 3.1
