### ISSUE TITLE
2.1 Dynamic Page Heading Implementation

### ISSUE THREAD

**Issue by NITHEESH107** [Mohith-Kumar-07/Student_schedule_App#14]
Description:
This PBI focuses on connecting the login form to the backend API to verify user credentials. Upon form submission, the Student ID and Password will be sent to the backend, which will validate whether the Student ID exists and the password matches the one in the database. Based on the validation result, the system will either allow the user to log in or display an error message.

Additionally, after a successful login, the page should display a dynamic heading that shows the current semester, year, and the student's first and last name. This information will be retrieved from the backend API to ensure it reflects the most accurate student and semester details.

Acceptance Criteria:

API Call:
Upon form submission, the login form sends the Student ID and Password to the backend API for verification.

Successful Login:
If the provided credentials are valid, the user is redirected to the Schedule View page.

The user session should be securely maintained throughout their interaction with the application.

Dynamic Heading: After login, the Schedule View page must display a dynamic heading in the following format:
"Welcome, [First Name] [Last Name] - [Semester] [Year]"
Example: "Welcome, Mohith Kumar - Fall 2024"

The heading should update based on the student’s information and the active semester details retrieved from the database.

Invalid Credentials:
If the credentials are invalid, an error message will be displayed:
"Invalid Student ID or Password"
The error message should be user-friendly and avoid exposing sensitive data.

Error Handling:
Handle and display appropriate error messages for failed API calls (e.g., server errors or timeouts).
Ensure the system can gracefully handle errors by showing a user-friendly message without exposing technical details.

**Comment by Mohith-Kumar-07** [comment]
Closing this issue since 2.1 and 2.2 were done together and hence will complete it using that issue.
