### ISSUE TITLE
2.2 Course Information Retrieval and Display

### ISSUE THREAD

**Issue by NITHEESH107** [Mohith-Kumar-07/Student_schedule_App#15]
Description:
This PBI focuses on connecting the login form to the backend API to verify user credentials. Upon form submission, the Student ID and Password will be sent to the backend, which will validate whether the Student ID exists and the password matches the one in the database. Based on the validation result, the system will either allow the user to log in or display an error message.

After a successful login, the Schedule View page will display:
A dynamic heading that shows the student’s first and last name, along with the current semester and year.
Course schedule details based on the student’s current enrollment, retrieved via SQL queries from the database.

Acceptance Criteria:
API Call:
On form submission, the Student ID and Password are sent to the backend for verification.

Successful Login:
Redirect to the Schedule View page on valid credentials.
Maintain a secure user session.

Dynamic Heading:
Display: "Welcome, [First Name] [Last Name] - [Semester] [Year]".

Course Schedule:
Fetch and display the following details for each enrolled course:
Course Number, Course Name, Section Number, Meeting Room, Meeting Days, Meeting Times.

Invalid Credentials:
Display "Invalid Student ID or Password" on login failure.

Error Handling:
Show user-friendly messages for API or system errors.

**Comment by Mohith-Kumar-07** [comment]
Linked it with another branch
