### ISSUE TITLE
2.3 User Interface (UI) Design and Responsiveness

### ISSUE THREAD

**Issue by NITHEESH107** [Mohith-Kumar-07/Student_schedule_App#16]
Description:
This PBI involves connecting the login form to the backend API to verify user credentials. Upon successful login, the user is redirected to the Schedule View page, which displays:

A dynamic heading with the student’s name, semester, and year.
The course schedule fetched via SQL queries from the database based on the student’s current enrollment.
A clear, readable, and user-friendly interface designed using HTML, CSS, and JavaScript, ensuring that the page is responsive across different screen sizes (desktop, tablet, and mobile).

Acceptance Criteria:

Login Verification:
Send Student ID and Password to the backend API and redirect on success.
Maintain a secure user session.

Dynamic Heading:
Display: "Welcome, [First Name] [Last Name] - [Semester] [Year]".

Course Schedule:
Display Course Number, Course Name, Section Number, Meeting Room, Meeting Days, Meeting Times.

Responsive UI:
Use HTML, CSS, and JavaScript to create a clean, adaptive layout.

Error Handling:
Show user-friendly messages for invalid credentials or system errors.

**Comment by Mohith-Kumar-07** [comment]
<img width="1710" alt="Screenshot 2024-10-30 at 2 36 26 PM" src="https://github.com/user-attachments/assets/312733f3-679f-4f05-be7a-a0b2f0306884">

**Comment by Mohith-Kumar-07** [comment]
Commited these changes along with 2.2
