### ISSUE TITLE
2 Schedule View

### ISSUE THREAD

**Issue by Mohith-Kumar-07** [Mohith-Kumar-07/Student_schedule_App#2]
Description:
This PBI focuses on creating a page where students can view the details of their course schedule for the current semester. The page will display dynamic information including course number, course name, section number, meeting room, meeting days, and meeting times, retrieved from the database based on the student's current enrollment.

Who:
Student

What:
View course schedule details

Why:
To manage time effectively and ensure timely attendance for all enrolled classes.

How:
Dynamic Page Heading:

The page heading will display: "{Semester, Year} Schedule for {Student First Name} {Student Last Name}". This will be dynamically generated using the student’s information and the current semester details.
Course Information:

Retrieve and display the following details for each course the student is enrolled in:
Course Number
Course Name
Section Number
Meeting Room
Meeting Days
Meeting Times
Display Logic:

Implement the frontend using HTML, CSS, and JavaScript to ensure the schedule is presented in a clear, readable, and user-friendly format.

Use SQL to retrieve course schedule details from the database based on the student's current enrollment.
Responsiveness:

Ensure the page adapts well to various screen sizes (desktop, tablet, and mobile).

Acceptance Criteria:

The Schedule View page should correctly display all enrolled courses with the following details:
Course Number, Course Name, Section Number, Meeting Room, Meeting Days, Meeting Times.

The Page Heading should accurately reflect the student's name, semester, and year dynamically.

The schedule data should be presented in a clear and readable format.

The information displayed should be retrieved from the database based on the student’s current enrollment.

The UI should be responsive and adapt to different screen sizes.

Proper error handling should be implemented if the student’s schedule data cannot be retrieved.

Story Points:
4

Additional Requirements:
User Experience (UX): Gather feedback from students to ensure the schedule view is easy to read and interact with.

Testing: Conduct tests to ensure the schedule is correctly displayed and dynamically updated based on the student's enrollment.

Error Handling: Implement fallback messages or error handling if the course schedule cannot be retrieved from the database.

**Comment by Ayas039** [comment]
Remember Me: Provide a "Remember Me" option to save user credentials for future logins.

**Comment by Ayas039** [comment]
Accessibility: Is the login page accessible to users with disabilities?

**Comment by Mohith-Kumar-07** [comment]
All sub issues under schedule view is done
