### ISSUE TITLE
1.2 Create student ID validation

### ISSUE THREAD

**Issue by Mohith-Kumar-07** [Mohith-Kumar-07/Student_schedule_App#7]
Description:
This PBI focuses on implementing front-end validation for the "Student ID" field in the student portal form. The validation will ensure that the Student ID follows the correct format and prevent submission if invalid data is entered. The format for the Student ID should strictly follow the pattern "V-XXXXXXXX" where:
"V" is a fixed character.
"XXXXXXXX" represents an 8-digit numeric value (each "X" is a number between 0-9).
The form must display appropriate error messages and block form submission until the correct format is entered

Acceptance Criteria -

The Student ID must follow the format "V-XXXXXXXX" (e.g., V-12345678).
If the format is incorrect, an error message will appear.

Empty Field Check:
If the Student ID field is empty, an error message will prompt the user to fill it.

Error Message Display:
The form will show clear error messages:
"Invalid format. Use 'V-XXXXXXXX'."
"Student ID is required."

Form Submission Block:
The form cannot be submitted until a valid Student ID is entered.

**Comment by Ayas039** [comment]
providing a sample ID format
